name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '13.2.1' # Specify the Xcode version you need

    - name: Install dependencies
      run: |
        sudo gem install cocoapods
        pod install

    - name: Run tests
      run: |
        xcodebuild test -scheme YourSchemeName -destination 'platform=iOS Simulator,name=iPhone 12,OS=latest'
